<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>重试多次</title>
  </head>
  <body></body>
  <script>
    function retry(fun, count, assert = () => false) {
      return new Promise(async (resolve, reject) => {
        let error = null
        for (let tryCount = 0; tryCount < count; tryCount++) {
          try {
            const value = await fun(tryCount)
            if (assert(value, tryCount)) {
              return resolve(value)
            }
          } catch (e) {
            error = e
          }
        }
        reject(new Error('多次尝试失败'))
      })
    }

    // retry(() => {
    //   throw new Error('错误')
    // }, 3).catch((e) => {
    //   console.log('e >>> ', e)
    // })

    let index = 0
    function createPromise(tryCount) {
      console.log('尝试次数：', tryCount)

      return new Promise((resolve, reject) => {
        index++
        setTimeout(() => {
          resolve(index)
        }, 1000)
      })
    }

    retry(createPromise, 10, (ret) => {
      return ret === 4
    })
      .then((res) => {
        console.log('当前的数据：', res)
      })
      .catch((e) => {
        console.log('捕获到错误 >>> ', e)
      })
  </script>
</html>
